### ISSUE TITLE
Ck2 encoding

### ISSUE THREAD

**Issue by TheDovahkiin97** [hmlendea/more-cultural-names#27]
here a copy paste:

So I made an odd discovery that may interest some of you looking at more historical localization. While CK2's localization files use Windows-1252 encoding, which mainly is oriented towards Scandinavian and Romance languages, it looks like the game can work with any Windows-12xx encoding type. For example, Windows-1250 swaps some Scandinavian and Romance characters for characters used in Polish, Czech, Slovak, Hungarian, Romanian, and Serbo-Croation, which may be of interest to people like @!'ⰘⰑⰓⰂⰀⰕ' (if they're still interested in CK2 modding). Windows-1253 swaps even more characters out and replaces them with Greek characters. Windows-1251 is Cyrillic, 1255 is Hebrew, 1257 is Baltic, 1254 is Turkish, and 1256 is Arabic (though a fairly shitty one).

my idea:
maybe the game can load multiple files with all the landed titles inside, which have different encodings for a few grouped cultures. A slavic file, latin file etc.

**Comment by hmlendea** [comment]
Huh, this is very interesting.
I'll take a look when I get some time.

I already started reorganising the data in this repo into a game-agnostic format (UTF-8 XML files) where all the names have their proper characters.
There will also be code (C# .NET Core) that will take that data and generate a mod for CK2 (replacing the characters that are not supported with close approximations or plain latin ones).
If the multiple files trick does indeed work, then I can integrate that in the generator and it'd be awesome.

Btw the main purpose for this "migration" is to prepare to support CK3 when it comes out, so that we can have a single central source for the localisations and use it in any number of games.
The work I've done so far is on the [dev](https://github.com/hmlendea/ck2-hip-mcn/tree/dev) branch

**Comment by TheDovahkiin97** [comment]
sounds awesome!
