### ISSUE TITLE
Arabic romanization system

### ISSUE THREAD

**Issue by stervel** [hmlendea/more-cultural-names#347]
I'm the guy who commented on the steam mod page, thought better post it here too.

I read the Roadmap that Arabic toponyms need work and I think I can help. I don't speak Arabic, but I have a working knowledge of reading Arabic script. May I know which Arabic romanization system is used in this mod before I do anything silly?

**Comment by hmlendea** [comment]
Hello.

Thanks for your interest in contributing to the project!

Currently, generally I take the ISO-233 names from the Wikipedia pages of individual locations, or I try to transliterate using a tool in some cases.

Examples:
|Arabic|Latin|
|-|-|
|أريحا|ʾArīḥā|
|ٱلنَّقَب|an-Naqab|
|إسدود|ʾIsdūd|
|إِسْرَائِيل|ʾIsrāʾīl|
|اسلو|Āslū|
|الأردن|Al-ʾUrdunn|
|الخليل|al-Khalīl|
|السامرة|as-Sāmirah|
|العمارنة|al-ʿAmārnah|
|بئر السبع|Biʾr as-Sabʿ|
|بابل|Babil|
|تشيشيناو|Tšīšīnāū|
|حركة المقاومة الإسلامية|Ḥarakah al-Muqāwamah al-ʾIslāmiyyah|
|حماس|Ḥamās|
|حَيْفَا|Ḥayfā|
|دمشق|Dimašq|
|رام الله|Rām Allāh|
|روما|Rūmā|
|سُورِيَا|Sūriyā|
|عَسْقَلَان|ʿAsqalān|
|غَزَّة|Ġazzah|
|فتح|Fatḥ|
|فِلَسْطِينَ|Filasṭīn|
|فهرج|Fahraǧ|
|مَنْف|Manf|
|هرتسليا|Hirtsiliyā|
|يوانينا|Īānīnā|

**Comment by stervel** [comment]
Thanks for responding. A question though.

I notice that most of bound tāʼ in a lot of place names (like in your example above "Ḥarakah al-Muqāwamah al-ʾIslāmiyyah") are either become ⟨h⟩ or omitted (e.g. `c_labla` as "Labla") while some adhere to the standard (using diaeresis t). Are these intentional?

**Comment by hmlendea** [comment]
A lot of the arabic names need updating. Many of them are not quite correctly transliterated for a few reasons, but usually because: a. many of them were added back when CK3 didn't exist and this mod only supported CK2, which had a **very** limited set of diacritics, and b. they were added a long time ago and were simply wrongly transliterated unfortunately.

So, I would say, when you see an arabic name that you think it's wrong, you're probably right and it's ok to change it.

**Comment by hmlendea** [comment]
Some of the intentional changes to the ISO-233 (1984):
 - `ah` instead of `ẗ` for the character `ة`
 - `ī` instead of `y` for the character `ي`
 - `th` instead of `ṯ` for the character `ث`
 - `ū` instead of `w` for the character `و`

This is done in order to adhere to the romanised names displayed on Wikipedia. If you have an objection to some of these, I might change it, especially for the characters `ẗ` and `ṯ` for which I'm not really sure which way to go, as they would still be displayed as "ah" and "th" in game anyway because none of the games supported by MCN has those characters and they're replaced when the mods are compiled.

**Comment by stervel** [comment]
I'm currently halfway through examining all the county titles in `e_spain` (because it's currently my fav region to play) and was completely unaware such intentional changes existed and blindly added romanization of all bound tāʼ in most names (I changed Labla as Lablaẗ).

Bound tāʼ will become /h/ or pausa only at the end of everything, anywhere else would be /t/ (such as "Qalʿaẗ ʾAyyūb" for Calatayud but "Qurṭubẗ" for Cordoba) or in construct state (example above should be "Ḥarakat al-Muqāwamat al-ʾIslāmiyyah"). With that convention, I guess `c_hama` "Ḥamāẗ" will be "Ḥamāah"?

Maybe the quick fix for bound tāʼ would be a script in the compiler to convert all instances of ẗ to h/Ø when it's the end of the entry possible?

The rest will be ok I guess, but I sense some awkward spelling may be happen because of it.

**Comment by hmlendea** [comment]
Yes, the builder can be updated to convert ẗ to h (or ah when it's not preceeded by an a already)
