### ISSUE TITLE
causes multiplayer lag

### ISSUE THREAD

**Issue by LonelyLullaby** [hmlendea/more-cultural-names#354]
Idk from what it seems when playing on hoi4 it opens a lot of timed decisions and when opening decisions it creates massive amounts of lag? why?

**Comment by hmlendea** [comment]
This is because in order to trigger name changes, this mod utilises hidden decisions.
It's normally not a problem and many mods, and even the base game, take this approach. However, since MCN grew to cover **a lot** of names, it's now uses so many of them that it became problematic.

Currently, I don't know of any alternative ways to handle name changes. If one is discovered, I will try to integrate it into MCN, although it would require this mod to be entirely reimplemented from scratch.
